language: python
fast_finish: true

python:
  - 3.6
  - 3.5

os:
  - linux

dist: trusty
group: edge

notifications:
  email: false

git:
  depth: 3

install: pip install -e .[tests]

script: coverage run tests/test.py -v

after_success: coveralls
